- name: Configure CloudSec web instances via SSM
  hosts: role_web
  serial: 1
  become: true
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3

# Use pre_tasks para validar a conexão ANTES das roles tentarem rodar
  pre_tasks:
    - name: Test SSM Sudo
      ansible.builtin.raw: sudo -n dnf help
      changed_when: false
      become: false  # O sudo já está no comando raw

  vars:
    app_bucket: "{{ lookup('env', 'APP_BUCKET_NAME') }}"

  roles:
    - cloudsec_web
