- name: Configure CloudSec web instances via SSM
  hosts: role_web
  serial: 1
  become: true
  gather_facts: false

  vars:
    app_bucket: "{{ lookup('env', 'APP_BUCKET_NAME') }}"

  roles:
    - cloudsec_web

    - name: Test SSM Sudo
      ansible.builtin.raw: sudo -n dnf help
      become: false