name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Digite DESTROY para remover os recursos e evitar custos"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  TF_VAR_allowed_public_ip_cidr: ${{ vars.ALLOWED_PUBLIC_IP_CIDR }}
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  TF_VAR_prowler_reports_bucket_name: ${{ vars.PROWLER_REPORTS_BUCKET }}
  TF_VAR_github_repository: ${{ github.repository }}
  PROWLER_REPORTS_BUCKET: ${{ vars.PROWLER_REPORTS_BUCKET }}

jobs:
  destroy:
    name: Destroy infrastructure
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform init
        run: terraform init

      - name: Terraform destroy
        run: terraform destroy -auto-approve