name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      confirm_apply:
        description: "Digite APPLY para confirmar a criação dos recursos na AWS"
        required: true
        type: string

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
  ADM_BUCKET_NAME: ${{ vars.ADM_BUCKET_NAME }}

  TF_VAR_allowed_public_ip_cidr: ${{ vars.ALLOWED_PUBLIC_IP_CIDR }}
  TF_VAR_ssh_public_key: ${{ vars.SSH_PUB_KEY }}
  TF_VAR_adm_bucket_name: ${{ vars.ADM_BUCKET_NAME }}
  TF_VAR_github_repository: ${{ github.repository }}
  TF_VAR_ansible_role_arn: ${{ vars.ARN_OIDC_ANSIBLE_ROLE }}
  TF_VAR_prowler_role_arn: ${{ vars.ARN_OIDC_PROWLER_ROLE }}

jobs:
  apply:
    name: Apply approved infrastructure
    runs-on: ubuntu-latest

    if: ${{ github.event.inputs.confirm_apply == 'APPLY' }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_TERRAFORM_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Terraform init
        run: terraform init -input=false -reconfigure

      - name: Terraform fmt
        run: terraform fmt -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -out=tfplan.binary

      - name: Convert plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Run Rego security policies before apply
        run: |
          opa eval \
            --fail-defined \
            --format pretty \
            --data ../policy/terraform_security.rego \
            --input tfplan.json \
            'data.terraform.security.deny[_]'

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan.binary

      - name: Get Terraform outputs
        id: tf_outputs
        working-directory: infra
        run: |
          APP_BUCKET_NAME=$(terraform output -raw app_bucket_name)
          echo "app_bucket_name=$APP_BUCKET_NAME" >> $GITHUB_OUTPUT

    outputs:
      app_bucket_name: ${{ steps.tf_outputs.outputs.app_bucket_name }}

  ansible:
    name: Configure EC2 with Ansible over SSM
    runs-on: ubuntu-latest
    needs: apply

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
      ADM_BUCKET_NAME: ${{ vars.ADM_BUCKET_NAME }}
      APP_BUCKET_NAME: ${{ needs.apply.outputs.app_bucket_name }}
      ANSIBLE_TIMEOUT: "60"
      ANSIBLE_HOST_KEY_CHECKING: "False"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_ANSIBLE_ROLE }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Validate ADM bucket access
        run: |
          aws sts get-caller-identity
          aws s3api head-bucket --bucket "$ADM_BUCKET_NAME"
          aws s3api get-bucket-location --bucket "$ADM_BUCKET_NAME"

      - name: Install Ansible and AWS dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible boto3 botocore
          ansible-galaxy collection install amazon.aws

      - name: Install AWS Session Manager Plugin
        run: |
          curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o session-manager-plugin.deb
          sudo dpkg -i session-manager-plugin.deb
          session-manager-plugin --version

      - name: Run Ansible over SSM
        env:
          ADM_BUCKET_NAME: ${{ env.ADM_BUCKET_NAME }}
        run: |
          ansible-playbook \
            -i ansible/inventory.aws_ec2.yml \
            ansible/playbook.yml
            
  prowler:
    if: false
    name: Run Prowler and upload report
    runs-on: ubuntu-latest
    needs: apply

    permissions:
      contents: read
      id-token: write

    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'us-east-1' }}
      ADM_BUCKET_NAME: ${{ vars.ADM_BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC - Prowler
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.ARN_OIDC_PROWLER_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Prowler
        run: pipx install prowler

      - name: Run Prowler AWS scan
        continue-on-error: true
        run: |
          prowler aws \
          --region "$AWS_REGION" \
          --output-formats html \
          --output-directory prowler-output

      - name: Upload Prowler HTML report to private S3 bucket
        run: |
          echo "Bucket: $ADM_BUCKET_NAME"

          REPORT_FILE=$(find prowler-output -name "*.html" | head -n 1)

          aws s3 cp "$REPORT_FILE" \
            "s3://$ADM_BUCKET_NAME/prowler/index.html" \
            --content-type "text/html"

          